# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SqliteDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SqliteDemo
  pod 'FMDB'

  target 'SqliteDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SqliteDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
